<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.2">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TmlBuildBootstrapFeatures>tomat.assethotreloading;tomat.enablemod;lolxd87.splashskip</TmlBuildBootstrapFeatures>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GoldMeridian.KeyGen" Version="1.0.1" PrivateAssets="All" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>